### ISSUE TITLE
mouse freezes when dragging a screen in Server Configuration on CentOS

### ISSUE THREAD

**Issue by Jnewbon** [symless/synergy-core#6507] opened 2019-05-23 09:51 UTC
### Operating Systems ###

Server: CentOS 7.5

### Synergy Version ###

Synergy 1: 1.10.2-stable-8c010140

### Steps to Reproduce ###

1. Open Server configuration 
2. Try to drag a new screen onto the grid or move an existing one.

Expected: New screen/move existing screen
Actual: mouse freezes and doesn't register clicks anymore. pressing Escreturns mouse control

### Extra Info ###

Possibly related to #6481 and #6487

**Comment by nbolton** [comment] 2019-10-25 06:55
Duplicate of #6487

**Closed by nbolton** 2019-10-25 06:55 UTC
Labels: bug, triage
