### ISSUE TITLE
Can’t switch screens using hotkey

### ISSUE THREAD

**Issue by agarzola** [symless/synergy-core#6484] opened 2019-04-22 14:59 UTC
Hi, I’m running into an issue where I can only seem to use hotkeys to switch from a client screen to the server screen, not the other way around. If my focus is on the server screen and I attempt to use a hotkey to switch to my client screen, nothing happens; focus remains on the server screen.

Here’s my config:
```config
# Synergy configuration file

# ---
# Declare all screens.
# ---
section: screens
  starbuck:
  ripley:
end

# ---
# Assign network names as aliases.
# ---
section: aliases
  starbuck:
    starbuck.local
    starbuck.lan
  ripley:
    ripley.local
    ripley.lan
end

# ---
# Arrange screens in a wrap-around fashion.
#
#   +------------+ +------------+
#   |            | |            |
# < |  starbuck  | |   ripley   | >
#   |            | |            |
#   +------------+ +------------+
# ---
section: links
  starbuck:
    left = ripley    # wrapping arrangement
    right = ripley   # normal arrangement
  ripley:
    left = starbuck  # normal arrangement
    right = starbuck # wrapping arrangement
end

# ---
# Set options.
# ---
section: options
  # Ctrl + Shift + Tab switches right.
  keystroke(control+shift+Tab) = switchInDirection(right)

  # Ctrl + Shift + h/j/k/l switches according to vim bindings.
  keystroke(control+shift+h) = switchInDirection(left)
  keystroke(control+shift+j) = switchInDirection(down)
  keystroke(control+shift+k) = switchInDirection(up)
  keystroke(control+shift+l) = switchInDirection(right)
end
```

I’m unable to switch from starbuck (server) to ripley (client) with either any of the keystrokes that I would expect to do so:
- `control+shift+Tab`
- `control+shift+l`
- `control+shift+h` (since I have the wrapping arrangement)

I tried the following to replace the last keystroke setting, to no avail:
```config
  keystroke(control+shift+l) = switchToScreen(ripley)
```

I’ve compiled `v1.x` on two computers running macOS Mojave (`10.14`, build `18A391`). Switching from ripley (client) to starbuck (server) works reliably, as stated above. Switching from starbuck to ripley does not. I’ve tried using `switchToScreen(ripley)` to explicitly switch to that screen (as opposed to infering it from the layout config and the direction via `switchInDriection()`), but this does not work either.

Other than the build, OS, and config above, is there any other information I can provide to help debug this issue?

---

_I originally posted in [this comment](https://github.com/symless/synergy-core/issues/5641#issuecomment-464458996), but since that issue is closed, I figured this warrants a new issue. Please let me know if you’d rather close this and re-open #5641 (since it was only closed for being stale)._

**Comment by Jnewbon** [comment] 2019-04-24 08:42
By the sounds of it both your computers are MacOS if so then this is probably related to #5796

**Comment by agarzola** [comment] 2019-04-24 12:14
I’ll keep an eye out for updates on that. Thanks for pointing me in that direction, @Jnewbon!

**Comment by Jnewbon** [comment] 2019-07-03 10:41
I'm going to mark this as a duplicate of #5796 and close this one

**Closed by Jnewbon** 2019-07-03 10:41 UTC
Labels: triage
