### ISSUE TITLE
Support Wayland in Synergy 1

### ISSUE THREAD

**Issue by ackstorm23** [symless/synergy-core#6690] opened 2020-05-19 18:35 UTC
### Problem ###

Support for Wayland is missing in Synergy 1, and the next major version is not scheduled to release until 2023, and may even take longer.  

[That is 9 years after it was requested in 2014](https://github.com/symless/synergy-core/issues/4090)

### Solution ###

Build basic/minimal support for Wayland in Synergy 1 to get us through to a more complete implementation in the next major version. 

### More Info ###

This is an embarrassingly long fulfillment time for a request that has a substantially large base of users behind it. Especially for a product which is not community funded. 

We are looking at close to or over a decade of waiting for support which has already been adopted as the default compositor on major distributions, while Xorg is only receiving minimal updates at this point going forward.

**Comment by stobbsm** [comment] 2020-06-02 14:53
Very important to have this! I use fedora as my daily driver, and with Xorg going into maintenance mode, synergy is pretty useless without wayland support. To the point where I will be pursuing a refund if this isn't taken seriously.

**Comment by Jnewbon** [comment] 2020-06-22 09:40
This is on our backlog as urgent and important, its only in the last year that Wayland has been displacing Xorg as the primary driver. 

Sadly this feature is not simple to implement and we haven't had the resources to dedicate to implementing it yet. It is something we are actively trying to change.

Duplicate of #4090

**Closed by Jnewbon** 2020-06-22 09:40 UTC
Labels: enhancement, triage

**Comment by danieldejager** [comment] 2021-11-14 00:42
I just upgraded ubuntu, and the paid for app isn't supported due to Wayland

**Comment by ackstorm23** [comment] 2021-11-14 00:46
> I just upgraded ubuntu, and the paid for app isn't supported due to Wayland

They only support legacy Xorg with their product. You'll have to manually roll back your Ubuntu configuration to support Xorg.

**Comment by danieldejager** [comment] 2021-11-14 00:50
> > I just upgraded ubuntu, and the paid for app isn't supported due to Wayland
> 
> They only support legacy Xorg with their product. You'll have to manually roll back your Ubuntu configuration to support Xorg.

Yup - was a quick change to make

**Comment by Triggs9** [comment] 2022-04-21 10:40
XWayland should allow you to run X11 applications under wayland. I lack the knowledge of how and theres very little documentation on it and the /usr/bin/Xwayland has about 3000 different parameters. seems a bit ironic for a "lets make it easy to support backwards compatibility of X11 applications in wayland" as is the XWayland moto. From XWayland site: "Wayland is a complete window system in itself, but even so, if we're migrating away from X, it makes sense to have a good backwards compatibility story." (https://wayland.freedesktop.org/xserver.html) yay modern computer obsfucation!

**Comment by nbolton** [comment] 2024-08-30 15:42
Fixed by: https://github.com/symless/synergy/pull/7449
