### ISSUE TITLE
GUI is too small on high DPI screens

### ISSUE THREAD

**Issue by nlyan** [symless/synergy-core#5609] opened 2016-09-23 09:43 UTC
### Operating Systems

Any/All
### Synergy Version

1.8.3-rc2
### Steps to reproduce bug
1. Open the GUI on a high DPI display (anything >100 dpi)
2. Observe that the main GUI is too small by a factor of DPI/100
3. Observe (on Windows) at least that checkboxes in the settings window render poorly
### Other info
- When did the problem start to occur? Unknown
- Is there a way to work around it? No
- Does this bug prevent you from using Synergy entirely? No

**Comment by XinyuHou** [comment] 2017-09-27 12:39
Duplicate of #6160

**Closed by XinyuHou** 2017-09-27 12:39 UTC
Labels: bug
