### ISSUE TITLE
Modifier keys stuck most of the time

### ISSUE THREAD

**Issue by laino** [symless/synergy-core#6239] opened 2018-01-08 17:23 UTC
### Operating Systems ###

Server: Windows 10 (Version 1709)
Client: Linux (Arch)

### Synergy Version ###

1.8.8-stable-c30301e

### Steps to reproduce bug ###

90% of the time, when moving the mouse connected to the Windows server to the Linux client,
some modifier key (Super, Shift, Alt...) will be stuck. Sometimes it is possible to make the key "unstuck"
by pressing it on the keyboard.

Might be related to being in some fullscreen application on Windows when you move the mouse to the screen border to switch desktops.

**Comment by XinyuHou** [comment] 2018-01-12 10:05
Duplicate of #4493

**Closed by XinyuHou** 2018-01-12 10:05 UTC
