### ISSUE TITLE
MacOS client (High Sierra) stops getting click events after some time

### ISSUE THREAD

**Issue by ndreisg** [symless/synergy-core#6201] opened 2017-11-21 10:13 UTC
### Operating Systems ###

Server: Windows 10 Version 1709 (Build 16299.64)
Client: macOS High Sierra Version 10.13.1

### Synergy Version ###

1.8.8-stable-25a8cb2

### Steps to reproduce bug ###

Yesterday i updated my macOS Version to "High Sierra" (10.13.1)
Now my synergy client on this mac stops getting click events after some time.

1. Synergy is running on both machines and has connected correctly.
2. Move mouse to the screen of the Mac.
3. Everything works fine.
4. Do not use the mouse for some minutes (actually 1 minute should be enough).
5. Now the mouse can still be moved around, but it can't click anymore.
6. Move mouse back to windows screen and then to Mac screen again.
7. Now everything works fine again.
8. repeat steps 4 - 7 as long as you like ;)

### Other info ###

* When did the problem start to occur? When I updated my macOS version to High Sierra (10.13.1)
* Is there a way to work around it? Yes, as described above, you can move the mouse back to Windows screen and then to Mac screen again to workaround the issue, but this workaround only works for a very short time and needs to be repeated very often.
* Does this bug prevent you from using Synergy entirely? No

Synergy Log does not show any helpful entries:

```
[2017-11-21T10:46:47] INFO: entering screen
[2017-11-21T10:46:47] WARNING: cursor may not be visible
[2017-11-21T10:46:47] INFO: leaving screen
[2017-11-21T10:46:47] WARNING: cursor may not be visible
[2017-11-21T10:46:47] INFO: entering screen
[2017-11-21T10:46:47] WARNING: cursor may not be visible
[2017-11-21T10:46:47] INFO: leaving screen
[2017-11-21T10:46:47] WARNING: cursor may not be visible
```

I don't know if this issue occurs in newer versions of Synergy, since my CEO has the login data to the Synergy account. I will update the issue when he's back :)

**Edit:** I just found out, that I actually have the latest Version of Synergy 1 installed.

**Comment by XinyuHou** [comment] 2017-11-23 13:13
Duplicate of #5976

**Closed by XinyuHou** 2017-11-23 13:13 UTC
