### ISSUE TITLE
When pasting picture from clipboard on os x, linux client goes dead.

### ISSUE THREAD

**Issue by CargoCoder** [symless/synergy-core#6164] opened 2017-10-08 11:45 UTC
### Operating Systems ###

Server: microOS Yosemite /El Capitan
Client: Debian 8 / Ubuntu 16.04

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

1. Copy picture into a clipboard on a linux client
2. Paste picture on OS X server
3. Linux client goes dead

### Other info ###

* I have similar setups at home and at work. OS X is always the server, several linux devices & usually one token windows device around. No issues with windows clients. Same issue on both locations w/ linux clients.
* The link on sending logs doesn't work :(, if I run client from bash in foreground (synergyc -f <ip>, the client just freezes)

**Comment by XinyuHou** [comment] 2017-10-11 11:03
This could be a duplicate of either #5820 or #5531

**Closed by XinyuHou** 2017-10-11 11:03 UTC
