### ISSUE TITLE
Wrong characters typed on client with Russian layout

### ISSUE THREAD

**Issue by Nixellion** [symless/synergy-core#6307] opened 2018-06-19 16:23 UTC
I've got an issue where whenever I try to type in Russian I get "????" instead. This issue is there if I use Windows as host and Windows as client.

Using Linux as Host and Windows as client - no problem, works fine.

But there's another problem, where some programs, like 3ds max, crash or hang often on the client if I have 'ru' on the host and 'en' on the client, and try to use any hotkeys. If I have 'us\en' on both host and client it seems to be working fine.

Latest 1.x stable (1.9.1 ?)

**Comment by nbolton** [comment] 2018-06-19 17:03
If you change your layout to US on the client, does it type correct characters?

**Comment by Nixellion** [comment] 2018-06-19 19:52
Here's what's going on. Using Windows Host and Windows Client:

Host ENG - Client ENG - Works fine
Host RUS - Client ENG - All characters are "????". Numbers work fine. Some special characters ( like № which is available in RUS layout on number 3 button) are also represented as ?. Basically any unicode characters seem to be represented as "?".
Host RUS - Client RUS - same thing

Changing layout on Client also forces change on Host when mouse is moved back.

Host RUS - Client change to ENG, if I start typing on client - host is also force d into ENG, and seems to work fine, since ENG+ENG works.

Both systems have US layout as default, and Russian Cyrillic as secondary.

---

Linux seems to be working fine though, I can type in RUS, but I can't use Mouse Back\Forward keys with Linux as a host. Back\Forward keys work ok with Windows host.

**Comment by nbolton** [comment] 2018-06-20 07:54
Thanks for the info, we plan to improve international keyboard support.

**Comment by Nixellion** [comment] 2018-06-20 20:21
Do you think that 3ds max crashes (only if RU layout is used) are related to this issue? I mean obviously it's not the case with a keyboard directly attached to a PC :)

**Comment by LeadManPL** [comment] 2018-06-21 16:00
@Nixellion you should report it in following issue which grabs together all KBD layoout problems: #6005

**Comment by Nixellion** [comment] 2018-06-21 16:11
@LeadManPL Thanks for the tip. I see you already linked the issue, should I copy my post there as well or is linking it enough?

**Comment by LeadManPL** [comment] 2018-06-21 17:33
@Nixellion I have no clue, I'm just client of Symless. Ask @nbolton

**Comment by ceco987** [comment] 2020-11-12 14:57
> Thanks for the info, we plan to improve international keyboard support.

@nbolton Do you have an estimate on when this will be fixed? I've seen multiple threads on this issue from years ago (like this one) and it's ongoing.

**Comment by andreacndn** [comment] 2020-11-16 12:13
@ceco987 we are currently wrapping up the release of Synergy 1.13.0, and then we'll start to work on these issues with international keyboards and characters.

**Comment by ceco987** [comment] 2020-11-16 12:14
I'm happy to hear that this issue is already addressed and hopefully will be fixed in the next version. Do you have an estimate on when 1.13.0 will be released? Thank you!

**Comment by andreacndn** [comment] 2020-11-16 12:16
We are planning to publish the release candidate 2 this week, likely on Slack and Discord, and depending on how the RC2 goes we'll plan the stable release in the following days.

**Comment by ceco987** [comment] 2020-11-16 12:21
> We are planning to publish the release candidate 2 this week, likely on Slack and Discord, and depending on how the RC2 goes we'll plan the stable release in the following days.

Amazing. Thank you for your time and support, may you and the whole team have a great week ahead! 😊

**Comment by ceco987** [comment] 2021-03-20 13:57
@andreacndn Hi, I'm currently using the most recent stable version (1.13.1.41) but the issue still persists. Any estimates on when this will be fixed? Thanks.

**Comment by ceco987** [comment] 2021-05-09 11:36
@nbolton Hi, can you please support us here regarding this issue? @andreacndn replied last on this topic, but his activity dropped. The issue is still present and has been for many years now. Are there any plans to get this fixed? Thank you.

**Comment by andreacndn** [comment] 2021-05-27 08:26
@ceco987 We are actively working on this issue, but we can't provide an estimate for its availability yet.

**Comment by ceco987** [comment] 2021-05-27 11:37
@andreacndn Thank you for your feedback, I hope it can be fixed at all, as it appears as a highly challenging case, being addressed first around 2014. Meanwhile, I'll keep developing my skills and maybe I'll join the effort for fixing the bug, once I have the needed knowledge.

Have a nice and productive rest of the week!

**Comment by vitalPixel** [comment] 2021-12-02 12:16
This should now be fixed with the release of Synergy 1.14.2.

If you're experiencing this problem please make sure you are running Synergy latest version (you can download it by logging in to your account here: https://symless.com/synergy/download).

Please let us know if you run into any issues.

**Closed by vitalPixel** 2021-12-02 12:16 UTC
Labels: bug

**Comment by ceco987** [comment] 2021-12-02 17:20
The language support is now indeed working independently on both the client and server, thank you for the fix. The only minor issue that I came across is that if the client is using the keyboard layout "Bulgarian (Traditional)", some of the characters are not mapped properly. (Specifically 'р' and 'л' which correspond to ',' and '.' on the US Intl. layout.). The exact layout of the Traditional Bulgarian Layout can be found on [this link](https://metodii.com/pic/k_bds_1.gif). Bulgarian Phonetic layout works without any issues, which is great.
