### ISSUE TITLE
Modifier keys stop working in Microsoft Remote Desktop

### ISSUE THREAD

**Issue by picchioni** [symless/synergy-core#5841] opened 2017-02-14 02:17 UTC
### Operating Systems ###

Server: Ubuntu 16.04 x64 or Windows 10 Professional
Client: macOS Sierra 10.12.3

### Synergy Version ###

1.8.7

### Steps to reproduce bug ###

1. Download Microsoft Remote Desktop from OS X App Store
2. Attempt to connect to Windows 10 machine remotely (Haven't tried other windows versions)
3. Attempt to utilize Shift key in combination with another key or any of the special keys and you'll notice they don't work

As a side note: They work just fine with another RDP tool called CoRD, however it has been abandoned and is unstable with later versions of OS X, making it not a viable solution.

### Other info ###

* Is there a way to work around it?: I have not found a workaround to date, short of utilizing a different app
* Does this bug prevent you from using Synergy entirely? No

Let me know if there's any other help I can provide.

**Comment by XinyuHou** [comment] 2017-02-28 18:03
Duplicate of #3083

**Comment by picchioni** [comment] 2017-02-28 18:25
@XinyuHou Interesting, I haven't experienced it in a VM yet, but I also use VMware Fusion instead of Parallels, perhaps the issue is application specific?

**Comment by XinyuHou** [comment] 2017-03-01 16:06
@picchioni 
Do you mean you can't the modifier keys on your local client machine, not inside of your remote session?

This behavior is highly likely application specific. Remote control and VM tend to handle input in their own ways which may conflict with Synergy

**Comment by picchioni** [comment] 2017-03-01 19:53
@XinyuHou Apologies for the confusion, I do mean that I can't utilize modifier keys inside my remote session. But the remote session in this case is RDP utilizing Microsoft Remote Desktop ([Link](https://itunes.apple.com/us/app/microsoft-remote-desktop/id715768417?mt=12)).  However another, significantly more unstable RDP client, [CoRD](http://cord.sourceforge.net/) works just fine, going back to your theory that it's very application specific.

I've personally never experienced an issue with modifier keys not working properly in a VM as a heavy VMware Fusion and occasional VirtualBox user.

Does that help at all?

**Comment by picchioni** [comment] 2017-05-04 16:23
We can add Royal TSX (Another RDP/VNC/etc... OS X App) to the list too where modifier keys aren't being passed though.

**Comment by sixsixtrample** [comment] 2017-05-11 15:45
Seconding the Royal TSX pains. @picchioni please ping me if you find a work around!

**Comment by BigBuckey** [comment] 2017-05-16 18:07
I am experiencing this issue with Parallels. Server: Windows 8.1 Pro, Client: macOS Sierra 10.12.4, Windows 10 VM in parallels. 

Shift, control, and Windows key do not work in the VM. They do work in the Mac (it's a CM Storm keyboard) Please let me know if I can post any logs/etc. and if there is a workaround. Caps lock doesn't work for special characters (which happen to exist in my Windows password) so I have a keyboard plugged into the Mac for now :(.

**Comment by picchioni** [comment] 2017-06-01 18:29
@BigBuckey sounds like another case of it being very app specific, because I use VMware Fusion on a daily basis (and VirtualBox once every blue moon) without a problem

**Comment by andrewr01** [comment] 2017-07-09 21:53
I use:
Server: PC, synergy-v1.7.5-stable-fa85a24-Windows-x64
Client: Mac synergy-v1.8.5-stable-a18eba7-MacOSX1011-x86_64.dmg

Parallels client works with all keys, Windows, Ctrl, Shift ...

I found the 1.8.6 Mission Control key fix broke the Windows key in Parallels. Getting really frustrated that I have to use such an old version to make things work!

**Comment by anon36** [comment] 2017-08-14 11:29
Still an open Issue?

**Comment by ajmathews** [comment] 2017-09-01 16:55
Any solution for this yet? 
Server: Windows 10
Client: macOS Sierra

Using Microsoft Remote Desktop, the ctrl, shift, windows and alt buttons do not work

**Comment by picchioni** [comment] 2017-09-01 18:21
@ajmathews Nope...and it's killing me everyday. *crying emoji*

**Comment by jupiterkenji** [comment] 2017-09-06 09:18
+1

**Comment by verchalent** [comment] 2017-09-06 13:05
+1 This is driving me to insanity. Also, you can add the Amazon Workspaces client to the list of apps.

**Comment by johnk73** [comment] 2017-09-09 21:04
+1 Just emailed support with this same issue.  Should have known I wasn't the first.  I hate the iMac keyboard but love the big display.  So where else would I want to remote desktop from?  Destination is Windows 8.  RDP is 8.0.42.
I'll give synergy-v1.8.5-stable-a18eba7-MacOSX1011-x86_64.dmg a try

**Comment by justinkauai** [comment] 2017-10-21 01:38
My workaround so far is to use xfreerdp but now my problem is XQuartz reverses my ctl <-> cmd system setting. cmd c cmd v is killing me!!!

**Comment by andrewr01** [comment] 2017-10-21 08:44
Parallels Client - you can switch the ctrl and command keys.

**Comment by andrewr01** [comment] 2017-10-23 07:38
Parallels Client - you can switch the ctrl and command keys.

**Comment by justinkauai** [comment] 2017-10-23 21:40
I actually couldn't get ctrl or cmd working in parallels client.  Shift works though.

**Comment by andrewr01** [comment] 2017-10-24 00:46
Did you go into Preferences > Keyboard and configure the ctrl and cmd keys?

**Comment by justinkauai** [comment] 2017-10-24 01:49
yeah i tried all combinations to no avail.

**Comment by hartmms** [comment] 2017-11-28 20:25
NX v5.3 client on Mac also has the same issue.

**Comment by skennedysocal** [comment] 2017-12-06 15:33
Add me to the list as well, I am stuck with using Synergy 1.8.5-stable-6a7703f on my Mac which means I have the terrible mouse lag as well. I am using my Mac mouse with my shared mechanical keyboard but it is a pain. I do not get Ctrl or Alt in my RDP clients but I do get Shift. This is both with the MS Remote Access and Parallels.

**Comment by sixsixtrample** [comment] 2017-12-06 15:36
Try using FreeRDP on Mac. It allows me to use all my keys.

**Comment by carceneaux** [comment] 2017-12-18 16:57
I really ❤️  RoyalTSX and it's a bummer because of this bug. I'm really enjoying Synergy 2, please fix. 😄

**Comment by celttechie** [comment] 2018-01-05 14:52
I was just having this problem yesterday with RoyalTSX.  I have my keyboard/mouse hooked up to a Linux system and then I use Synergy 2.0.4 to control my Mac, running RoyalTSX.  I had Royal TSX open an RDP session to a Windows box and was trying to use the shift key to log in on a web page on the Windows system.  I finally found that if I go into Remote Desktop Connection Settings|Advanced|Input and select "Send key presses as Unicode" it sends the right characters when using my Shift key.  Try it out, maybe it'll help you.  :)

**Comment by carceneaux** [comment] 2018-01-05 15:24
@celttechie That did it! Thank you so much! For those following the instructions in the previous post, edit the **Properties** of each Windows RDP session to access the *Remote Desktop Connection Settings | Advanced | Input* area.

**Comment by melliott-sis** [comment] 2018-01-12 18:04
@celttechie Thanks for sharing this. I'd been looking for a fix for ages. I'm using Windows as a synergy server, OSX as a client. Shift now works un Royal TSX, but the ctrl key modifier does not. Much less of an issue for me, but I wanted to share.

**Comment by carceneaux** [comment] 2018-01-12 18:49
@melliott-sis I had this issue at first as well. To resolve this, all I had to do was go to the same area as before *Remote Desktop Connection Settings | Advanced | Input* and check the options for **Windows Keys Passthrough** and **Remap macOS keyboard shortcuts to their Windows equivalent**.

![image](https://user-images.githubusercontent.com/17179966/34890276-45d9679e-f79f-11e7-919a-b7b97e1df8fc.png)

**Comment by andrewr01** [comment] 2018-04-08 23:58
@carceneaux You reckon ticking the Remap macOS keyboard shortcuts to their Windows equivalent makes the Ctrl and Alt keys work? I can't get those keys to work.

**Comment by carceneaux** [comment] 2018-08-02 16:40
I experienced this issue in **Remote Desktop Manager** on my Mac as well. The solution was to:

* Edit the properties of each RDP connection that I  had created
* Navigate to the **Microsoft Remote Desktop (RDP)** --> **Local Resources** tab
* Change the *Keyboard layout* from **Invariant Language (Invariant Country)** to **English**.

![image](https://user-images.githubusercontent.com/17179966/43597621-9f5595cc-9650-11e8-976a-d447da433783.png)

@XinyuHou I agree with @dnapier that this isn't a Synergy specific issue but is exacerbated by how some applications receive their keyboard inputs.

**Comment by justinkauai** [comment] 2018-08-02 19:33
@carceneaux and Remote Desktop Manager just made my day!
Finally no more training my brain to use a different modifier key for RDP.

**Comment by andrewr01** [comment] 2018-08-21 21:45
@carceneaux, what is Remote Desktop Manager? Is it [this](https://mac.remotedesktopmanager.com/)? IT's a bit expensive at $150 USD!

**Comment by sixsixtrample** [comment] 2018-08-21 21:49
@andrewr01 the free version is free.

**Comment by andrewr01** [comment] 2018-08-21 21:54
@sixsixtrample Thanks for that. That sounds like a good deal!

**Comment by johnk73** [comment] 2018-08-21 21:58
There is a free version on their website (Remote Desktop Manager "Free
Edition").  https://remotedesktopmanager.com/home/downloadfree

**Comment by andrewr01** [comment] 2018-08-21 23:33
Well I tried Remote Desktop Manager free version with the settings @carceneaux posted but still can't get Shift, Ctrl, Alt or the Windows key to work in the RDP session. That's with Synergy 1.10.0 on PC and Mac. The only RDP app that works for me is Parallels, but I have to revert to 1.8.5 on the Mac or the Windows key won't work.

**Comment by MartinRJ** [comment] 2020-02-03 00:06
Still not fixed.

**Comment by asidler** [comment] 2020-03-25 20:46
Had the same issue. 
Switched to 'Barrier' a fork of Synergy. They seem to have fixed this.

**Comment by devnall** [comment] 2020-03-26 20:35
Add MacOS Catalina's native Screen Sharing.app to the list of remote desktop clients through which Synergy won't pass modifier keypresses (shift, control, option/alt, command/windows).

Synergy server on Win10, Synergy client on Catalina (both 1.11.0 stable). That works fine. But if I run Screen Sharing.app on the Mac to connect to a second Mac, it won't pass control/shift/option/command through the screen sharing session.

Switching to Barrier fixed my problem.

**Comment by verchalent** [comment] 2020-04-03 15:31
Confirmed, switching to barrier resolved the issue for me. Would really like to see Synergy pull the fix in.

**Comment by jscott0918** [comment] 2021-07-21 13:05
Been like this for years, only lead I found was reverting to a very old synergy version in a very old forum post.

**Comment by mohitt** [comment] 2021-11-02 23:38
Today is Nov 2 2021, still no fix of this one. I am paid customer for quite a some time. But, this is disappointing. @nbolton this works in barrier. Can something be done for this ticket.

**Comment by vitalPixel** [comment] 2021-12-02 12:18
This should now be fixed with the release of Synergy 1.14.2.

If you're experiencing this problem please make sure you are running Synergy latest version (you can download it by logging in to your account here: https://symless.com/synergy/download).

Please let us know if you run into any issues.

**Closed by vitalPixel** 2021-12-02 12:18 UTC
Labels: bug
