### ISSUE TITLE
Cursor gets stuck off screen on Windows server

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#6479] opened 2019-04-10 11:29 UTC
### Operating Systems ###

Windows 10 on both

### Synergy Version ###

v1.10.1

### Steps to reproduce bug ###

1. Move mouse off server screen
2. See that mouse doesn't appear on client
3. Unable to move mouse back to server

**Comment by nyetwurk** [comment] 2019-04-11 05:57
Affects 1.9.1 as well

**Comment by nyetwurk** [comment] 2019-05-16 23:52
Affects 1.10.2 as well

**Comment by Jnewbon** [comment] 2019-10-09 09:27
Duplicate of #5294

**Closed by Jnewbon** 2019-10-09 09:28 UTC
Labels: bug
