### ISSUE TITLE
Keyboard  Language Support

### ISSUE THREAD

**Issue by Goldenstarc** [symless/synergy-core#6183] opened 2017-10-28 20:46 UTC
### Operating Systems ###
Server: Windows 10 1607
Client: Windows 10 1607
### Synergy Version ###
1.8.8
### Issue ###
i have two keyboard lang. enabled  on my both Windows (English and Persian)
BUT when im in PER and i switch form SERVER to CLIENT every Persian character that i type in CLIENT becomes "?" 
(although i can type Persian with my client OWN keyboard and SERVER very well)
(It is clear that there is no problem when im in ENG and i switch from one screen to another)

**Comment by XinyuHou** [comment] 2017-11-01 12:14
Duplicate of #4344

**Closed by XinyuHou** 2017-11-01 12:14 UTC
