### ISSUE TITLE
Tray icon no longer available in gnome 3.26

### ISSUE THREAD

**Issue by andreanidouglas** [symless/synergy-core#6173] opened 2017-10-13 02:09 UTC
### Operating Systems ###

Server: Windows 10 64bit Pro
Client: Arch Linux
### Synergy Version ###

1.8.8--

### Steps to reproduce bug ###

Once start program on version 3.26.1 of gnome desktop, the error appears "System tray is unavailable, don't close your window", since system tray was deprecated from this version of the gnome environment

**Comment by XinyuHou** [comment] 2017-10-18 14:53
Duplicate of #5304

**Closed by XinyuHou** 2017-10-18 14:53 UTC
