### ISSUE TITLE
SSL connection drops because of client is dead error

### ISSUE THREAD

**Issue by ucirello** [symless/synergy-core#5857] opened 2017-02-22 18:41 UTC
### Operating Systems ###

Server: macOS X 10.12.13
Client: macOS X 10.12.13

### Synergy Version ###

1.8.7-stable-9799e96

### Steps to reproduce bug ###

Sudden "client is dead" and complete loss of state.

### Other info ###

* Change screens with a wait of 350ms
* Checking client every 1000ms
* Use mouse relative positioning
* No hotkeys set.

```
[2017-02-22T09:51:41] INFO: switch from "client.local" to "server" at 1441,2
[2017-02-22T09:51:41] INFO: entering screen
[2017-02-22T09:54:30] NOTE: client "client.local" is dead
[2017-02-22T09:54:32] INFO: OpenSSL 1.0.2 22 Jan 2015
[2017-02-22T09:54:32] INFO: accepted secure socket
[2017-02-22T09:54:32] INFO: AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
[2017-02-22T09:54:32] NOTE: accepted client connection
[2017-02-22T09:54:32] NOTE: client "client.local" has connected
[2017-02-22T09:55:04] NOTE: client "client.local" is dead
[2017-02-22T09:55:06] INFO: OpenSSL 1.0.2 22 Jan 2015
[2017-02-22T09:55:06] INFO: accepted secure socket
[2017-02-22T09:55:06] INFO: AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
[2017-02-22T09:55:06] NOTE: accepted client connection
[2017-02-22T09:55:06] NOTE: client "client.local" has connected
[2017-02-22T10:07:01] INFO: switch from "server" to "client.local" at 1602,1439
[2017-02-22T10:07:01] INFO: leaving screen
```

**Comment by XinyuHou** [comment] 2017-03-01 12:06
@ccirello 
Is this an infinite loop?

Please try to disable clipboard sharing.

**Comment by ccirello** [comment] 2017-03-01 15:27
Not an infinite loop.
Clipboard sharing is disabled in this case. It was my first attempt to fix the problem before opening this issue.

**Comment by elcman** [comment] 2017-04-06 20:46
Sorry, taken me some time to get back to this, but when I changed logging state to debug on the server. I got a series of No-ops. But when I enabled debug on the client side, it seems to resolve the issue for that immediate time. Do you want logs from both client and server, or would one be more appropriate over the other?

**Comment by kutschinsl** [comment] 2017-04-07 15:26
In reference to [#5939](https://github.com/symless/synergy/issues/5939), I am still getting the issue when WebEx is open with "Use SSL" disabled on both client and host.

**Comment by JPerham** [comment] 2017-04-13 19:11
+1 to Kutschinsl issue with WebEx - I experience the same thing, two different clients test, same server, same result. Clients were both Win 10 pro - current test machine is running build 14393.693

Willing to pull any needed logging (wireshark, or otherwise) 

of note, I did notice process crashes in the event viewer on my old client machine. I can reproduce with procmon running if that would be helpful as well. 

Synergy is running 1.8.7-stable-9799e96

**Comment by xpac1985** [comment] 2017-04-28 14:34
#5939 is not a duplicate of this, I ask you to reopen the other ticket. It is not SSL related.
More debug information can be found in #5939

**Comment by zeroepoch** [comment] 2018-05-30 22:32
Seeing the webex freezing issue still with 2.0.11

**Closed** 2019-01-06 17:03 UTC
Labels: bug
