### ISSUE TITLE
single quote and double quote not working on MacOS client

### ISSUE THREAD

**Issue by Dawieder** [symless/synergy-core#6186] opened 2017-11-05 15:12 UTC
### Operating Systems ###

Server: Windows 10
Client: MacOS Sierra

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

1. Start any editting tool
2. Type double quote
2. Try double quote followed by space
3. Nothing is being typed

### Other info ###

I already tried switching keyboard on the MacOS client, none of the keyboards work. 
Tried keyboards: US, US Internationa, ABC, ABC Extendend, Dutch

Output from debug:

[2017-11-05T15:59:11] DEBUG1: recv key down id=0x0000efe1, mask=0x2001, button=0x002a
[2017-11-05T15:59:11] DEBUG1: mapKey efe1 (61409) with mask 2001, start state: 0000
[2017-11-05T15:59:11] DEBUG1: find best:  0000 2001
[2017-11-05T15:59:11] DEBUG1: best key index 1 of 1 (exact)
[2017-11-05T15:59:11] DEBUG1: found key in group 0
[2017-11-05T15:59:11] DEBUG1: state: 0000,0000,0000
[2017-11-05T15:59:11] DEBUG1: flip: 0000 (0000 vs 0000 in 0000 - 0000)
[2017-11-05T15:59:11] DEBUG1: desired state: 2001 0000,0000,0000
[2017-11-05T15:59:11] DEBUG1: flip: 0000 (0000 vs 2001 in fffe - 6020)
[2017-11-05T15:59:11] DEBUG1: mapped to 039, new state 0001
[2017-11-05T15:59:11] DEBUG1: keystrokes:
[2017-11-05T15:59:11] DEBUG1:   button=0x0039 virtualKey=0x0038 keyDown=down
[2017-11-05T15:59:11] DEBUG1: recv key down id=0x00000022, mask=0x2001, button=0x0028
[2017-11-05T15:59:11] DEBUG1: mapKey 0022 (34) with mask 2001, start state: 0001
[2017-11-05T15:59:11] DEBUG1: key 0022 is not on keyboard
[2017-11-05T15:59:11] DEBUG1: recv key up id=0x00000022, mask=0x2001, button=0x0028
[2017-11-05T15:59:12] DEBUG1: recv key up id=0x0000efe1, mask=0x2000, button=0x002a
[2017-11-05T15:59:12] DEBUG1: new state 0000
[2017-11-05T15:59:12] DEBUG1: keystrokes:
[2017-11-05T15:59:12] DEBUG1:   button=0x0039 virtualKey=0x0038 keyDown=up
[2017-11-05T15:59:27] DEBUG1: recv mouse down id=1
[2017-11-05T15:59:27] DEBUG1: faking mouse button id: 0 press: pressed
[2017-11-05T15:59:27] DEBUG1: recv mouse up id=1
[2017-11-05T15:59:27] DEBUG1: faking mouse button id: 0 press: released

**Comment by XinyuHou** [comment] 2017-11-23 12:30
Duplicate of #4280

**Closed by XinyuHou** 2017-11-23 12:30 UTC
