### ISSUE TITLE
Client tray language switcher reverts to EN

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#6506] opened 2019-05-23 09:01 UTC
### Operating Systems ###

Server: Windows 7
Client: Windows 10

### Synergy Version ###

1.10.1

### Steps to Reproduce ###

1. Use language to EN on server
1. Change my language on the client from EN to HEB
2. Move the mouse from server to client and start typing

Expected: HEB chars are typed on the client
Actual: Client tray language switcher reverts back to EN

### Extra Info ###

Also, output on the client is sometimes shown as "?????" instead of the actual letters. This is intermittent.

Workaround: Go back to the server and change the language to HEB, then move the mouse back to the client and start typing

Original wording from @Axlyted from issue #5798:

> 
> I got the following setup:
> 
> windows 7 desktop ~ server
> windows 10 laptop ~ client
> 
> When I use synergy on my laptop and I change my language from EN to HEB for example.. it seems like the language switch is working well(I can see that in the botton toolbar).. but as soon as I start typing.. it revert to the previous language... the only "solution" at the moment is go back to my desktop screen.. change the language and then move my mouse to my laptop. it's not actually solution you know..
> 
> I think the previous version (1.8.4) didn't had this issue. Is there somewhere I can get this version instead? I mean, In case you don't have a solution for me.
> 
> Also.. when I change language, it's shown as "?????" instead of the actual letters... sometimes it works accordingly but sometimes it doesn't

@jack17529 @radevop @javarool @idsoftgit @0xmono

**Comment by nbolton** [comment] 2019-05-23 09:03
@Axlyted Do the steps above accurately describe the bug?

**Comment by DMinsky** [comment] 2019-07-24 11:19
I have the same issue.
Server: MacOS 10.14.6 (18G84), two input sources EN and Russian PC
Client: Windows 10 (1809), two input sources EN and Russian
Synergy version: 1.10.2-stable-8c010140 both client and server.

When I switch keyboard layout on Mac Server everything works great on Mac and PC. But when I try to switch layout on PC Client, the icon is switched to target layout, but immediately after I press any "character" key on keyboard is switch back to language set on Mac Server and use the input layout set on Mac Server.

**Comment by xuduo18** [comment] 2020-07-27 20:28
Still happening. Very annoying. I switch between ubuntu and Win10 and on Win 10 the input method keeps switching to Chinese.

**Comment by 0xmono** [comment] 2020-07-27 20:41
The problem is more than 3 years old and it looks like it will never be fixed. Previos discussion https://github.com/symless/synergy-core/issues/5798

**Comment by nachevn** [comment] 2020-09-24 09:32
@nbolton any update on this?

I'm using Ubuntu 18.04 as Synergy server and Windows 10 with running Arch Linux VM inside and trust me, switching the language on the server side as proposed by you in the description is complicated as it sounds and it doesn't work, especially inside the Arch Linux VM on the Windows 10 client. I would really appreciate if this feature gets implemented.

Best regards
Niko

**Comment by VladimirMakaev** [comment] 2020-11-18 12:12
This is super annoying thing for me. I'm using Mac as a server and Windows as a client. To switch between Russian/Eng I have to go back to Mac. Please fix it!

**Comment by ignacionr** [comment] 2020-11-19 06:05
Здравствуйте @VladimirMakaev . Since I am currently assigned to tracking international character code-related issues, and plus because me too I often switch EN-РУ, will personally take care of this within our two week sprint.

**Comment by VladimirMakaev** [comment] 2020-12-24 17:35
@ignacionr It's been 2 months. Where is the fix?

**Comment by ignacionr** [comment] 2020-12-27 10:38
Dear @VladimirMakaev Thank you for keeping up here! It is truly encouraging to receive feedback and interest. You obviously deserve an honest explanation. Unfortunately, the bigger release meant that my time needed to be reallocated to other items that have been identified as affecting a bigger number of our users.
Nevertheless, I will keep advocating for this item. As said before, I am on the same boat as a daily user of Synergy.

In any case, please understand this is not going to be a super easy fix. It is more a refactoring of how keys are re-interpreted on the client side. I might at some point need to bother you with your opinion on a couple of alternatives. Please bear with us. And many thanks for being part of this community!

Sincerely, Ignacio.//

**Comment by kiril-daskalov** [comment] 2021-03-24 10:52
Up

**Comment by erjanmx** [comment] 2021-07-26 08:00
sprint hasn't finished yet :)

**Comment by orangeBisquit** [comment] 2021-08-14 14:47
Can you please finally fix it?

**Comment by orangeBisquit** [comment] 2021-08-17 16:11
Guys, I'm recomending using sharemouse app, it's free and no issue with switching between languages. Symless are just not interested in fixing this bug, so I switched and I'm finally enjoying using one keyboard with two laptops.

**Comment by vitalPixel** [comment] 2021-12-02 12:17
This should now be fixed with the release of Synergy 1.14.2.

If you're experiencing this problem please make sure you are running Synergy latest version (you can download it by logging in to your account here: https://symless.com/synergy/download).

Please let us know if you run into any issues.

**Closed by vitalPixel** 2021-12-02 12:17 UTC
Labels: bug
