### ISSUE TITLE
Modifier Keys stop working on a VM on Mac client

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#3083] opened 2014-10-13 06:29 UTC
**Imported issue:**
- Author: Ed Farnbauch
- Date: 2012-04-09 15:03:12
- Legacy ID: 3153
- Version: 1.4.7

**Steps to reproduce:**  
1. setup vm in vmware fusion  
2. start synergy  
3. Attempt to use modifier keys on any window in VM  

Expected: Modifier keys work (ie. shift produces capital letters)  
Actual: Produces just the unmodified key (T is t, or <ctrl-T> is t)  

**Versions (Synergy, OS):**  

Server:  (Linux (has tested on Fedora, Mint, and RHEL 6)  
Client 1: 1.47 (Mac OS X 10.7 (all versions))  
(though this has been an issue for several versions)  

**Workaround:**  

I can use caps lock to get a capital letter. but not for any of the other modifier keys

**Comment by the-wes** [comment] 2016-05-16 08:39
A user sent in this information:

The Command key does get detected properly. Pressing Shift along with a character does not result in seeing a capital letter. Also, pressing Ctrl-Option does not generate the same keystroke through Synergy that it does with the physical keyboard. The Ctrl-Option combination is used in Parallels to release focus on the VM so the keyboard and mouse control revert back to the OS.

I ran showkeys in the terminal on Fedora in the VM and found the following:

Physical keyboard:

Press and release shift: 
keycode 42 press 
keycode 42 release 
Press and release control: 
keycode 29 press 
keycode 29 release 
Press and release option: 
keycode 56 press 
keycode 56 release 
Press shift, then Z, release Z, release shift: 
keycode 42 press 
keycode 44 press 
keycode 44 release 
keycode 42 release

The last combination also displays an uppercase Z on the terminal window.

**Comment by lordarcy** [comment] 2016-05-20 13:38
I was the user that sent in the details the-wed mentioned on May 16. More details of the environment:

Server = Mac OS 10.10.5 Yosemite
Client = Mac OS 10.11.4 El Capitan
Using Parallels Desktop 11.2.0.32581
VM = Fedora 23

**Comment by kryojenik** [comment] 2016-06-29 14:31
Server = Mac OS 10.9.5
Client = Mac OS 10.11.4 El Capitan
Using Microsoft Remote Desktop 8.0.31

Modifier keys in Microsoft Remote Desktop are ignored

**Comment by TryTryAgain** [comment] 2016-07-14 18:10
Confirmed by me for a while as well, very painful.
Software: Microsoft Remote Desktop 8.0.32 (Build 27142)
Host: Ubuntu 16.04
Client: OSX 10.11.5 Desktop, worked with CoRD and others, must be a Synergy OSX Client --> Microsoft Remote Desktop issue :(

**Comment by lordarcy** [comment] 2016-07-17 16:46
As a work-around if you are only using a Mac as both host and client is to use Teleport until this can get fixed.

**Comment by melliott-sis** [comment] 2016-10-14 19:42
This is an issue for me as well
Host: OS X 10.11.16
Client: OS X 10.11.16
Shift key does not work inside Remote Desktop or Royal TSX

**Comment by kryojenik** [comment] 2016-10-14 20:41
I switched to sharemouse for this reason.

**Comment by hgijeon** [comment] 2016-12-14 15:38
This makes me crazy right now. I can't even type any uppercase letters in Parallels VM.

Synergy = 1.8.6-stable-2ab21aa

Server = Ubuntu 16.04
Client = Mac OS 10.12.2 Sierra

Using Parallels Desktop 12.1.1 on Client(Mac)
VM = Windows10 Pro 1607

**Comment by lordarcy** [comment] 2016-12-14 19:01
I am using Synergy 1.7.4 on my server and client Mac (Yosemite on server, El Capitan on client) and the modifier keys are working now. I'm not sure what happened because I didn't write down the version of Synergy that I was using back in May. I've uninstalled and reinstalled Synergy on both computers several times.

**Comment by Spasi** [comment] 2017-01-27 11:28
Same issue. Setup:

Server = Windows 10
Client = macOS Sierra 10.12.3
VM = Ubuntu 16.04 running on Veertu Desktop

**Comment by sdcarpenter** [comment] 2017-06-10 03:19
I've submitted a pull request that address this bug for the most recent version of Parallels and Synergy. Unfortunately the fix is currently specific to Parallels and a bit of a hack (https://github.com/symless/synergy/pull/6064). If the owners find it useful, perhaps we can extend this fix to the other apps mentioned in this bug.

**Comment by fidesachates** [comment] 2017-07-09 17:20
Confirmed issue and would very much like a fix. 

Server: Windows Server 2008
Client: Mac OSX 10.12.4
VM: Windows 10 on Parallels

**Comment by bricerebsamen** [comment] 2017-09-07 18:16
confirmed issue and would very much like the fix to get merged and a new version released.
Server: Ubuntu 14.04
Client: Max OSX 10.12.5
VM: Ubuntu 14.04
Synergy: 1.8.8

**Comment by jorhett** [comment] 2017-09-19 20:46
@nbolton why do you keep marking this obsolete and legacy and what have you, without any fix?

**Comment by iMilnb** [comment] 2017-11-09 13:38
This bug still occurs with synergy-core 2.0.0

Server: Linux Mint 18
Client: Debian 9 on Parallels 13.1.1 (macOS 10.12.6)

**Comment by chewph** [comment] 2017-11-16 05:49
When is this problem ever going to be resolved?

**Comment by carceneaux** [comment] 2018-04-21 13:01
I have a workaround for this! 

* Connect a USB keyboard directly to your Mac *(It doesn't have to be the same keyboard Synergy is using.)*.
* Press the *Num Lock* key and verify numpad is now working properly.
* Disconnect USB keyboard and the settings stick.

**Comment by benedmunds** [comment] 2018-07-23 17:44
Bump

**Comment by brabidou** [comment] 2018-08-05 19:53
BUMP! Looks like this has been a bug for years now. How has Synergy not address this? This issue is all over the Synergy forums.

**Comment by Garbee** [comment] 2019-03-11 14:53
I had to be just adding more oxygen to the flame. But this issue is now 7 years old. Meanwhile, anyone who is stuck developing inside of, at least, Windows VMs on a Mac is hosed for using Synergy at all. If I need to keep another keyboard around to get basic keystrokes into a VM, I might as well just use a whole second keyboard and mouse.

Is there any kind of update that could be given as to if this is even on the dev team's roadmap of things to look at in a given quarter/year? Or should those of us needing a virtual KVM solution look elsewhere if we need to use Parallels?

**Comment by MartinRJ** [comment] 2020-02-03 00:06
Still not fixed.

**Comment by vipzen** [comment] 2020-02-03 02:51
I'm having the same issue. Two Macs, server is Catalina, cliente is Mojave running Parallels 14.

**Comment by rajlego** [comment] 2020-04-29 03:10
Same issue on parallels 15.

**Comment by vitalPixel** [comment] 2022-04-27 09:57
This should now be fixed with the release of Synergy 1.14.2.

Can someone confirm if they still experience this issue when running Synergy's latest version?
You can download it by logging in to your account here: https://symless.com/synergy/download

**Comment by sdcarpenter** [comment] 2022-04-28 20:17
@vitalPixel I can confirm this is working for me now!

**Comment by vitalPixel** [comment] 2022-05-12 08:57
Thanks for confirming @sdcarpenter , that's great to know.

I'll close the issue now.

**Closed by vitalPixel** 2022-05-12 08:57 UTC
Labels: bug
