### ISSUE TITLE
Client freezes intermittently for a few seconds

### ISSUE THREAD

**Issue by ezakto** [symless/synergy-core#6481] opened 2019-04-16 16:07 UTC
### Operating Systems ###

Server: Ubuntu 18.04
Client: Ubuntu 18.04 / Windows 7

### Synergy Version ###

1.10.1

### Steps to reproduce bug ###

I don't know how to reproduce it. I'm just typing most of the time, and when this freeze happens, it often keeps typing the last key I pressed (and I end with something like "hhhhhhhhhhhhhhhhhhhhhh" in the text editor, or deleting several words). Happens randomly, sometimes in spans of 10 seconds, sometimes minutes.

### Other info ###

* When did the problem start to occur? I'm not sure, but I think it started when I upgraded to 1.10
* Is there a way to work around it? No
* Does this bug prevent you from using Synergy entirely? No, but it's SO annoying that I'm thinking about stop using it

Client log: https://pastebin.com/yktGcWtZ
Server log: https://pastebin.com/ErFbn1Wy

When it freezes, it freezes for random times, between 2 and 10 seconds. The client logs several "found key in group 0" when it freezes, while server logs "Cursor is locked to screen, check Scroll Lock key". I'm not pressing the lock key.

**Comment by Jnewbon** [comment] 2019-04-23 09:00
Hi, 
The string "found key in group 0" is logged when a user-defined hotkey is pressed on a client. could you check your hotkey settings [Configure Server] -> [Hotkeys] and see if any of them are bound to unexpected keys, as there seems to be a lot of them being logged.

There are some known issues related to Ubuntu being the server. Would it be possible to try setting the windows machine as the server to see if the problem goes away?

**Comment by ezakto** [comment] 2019-04-23 13:53
Hey @Jnewbon, thanks for your input. I have no hotkeys configured.
And sadly I have no windows machine to use as a server right now, but I'll try to do some tests whenever I can.

I had to disable Synergy last week because it's impossible to work like this.

**Comment by deanranderson** [comment] 2019-04-24 23:46
I have the same issue with Windows 10 server, Ubuntu 18.04 client.

I'm not seeing anything in the Log when it happens.

**Comment by pjwerneck** [comment] 2019-04-25 22:07
I have the same issue with 1.10.1 on Kubuntu 18.04 server an two clients. Upgraded to synergy 2.0.12 and the problem persists. 1.10.1 worked fine on Kubuntu 16.04.

**Comment by jgindin** [comment] 2019-04-30 11:54
I had to stop using Synergy because of this bug...In addition to freezes, I would often see behavior as if a key was stuck down. My desk is now over-crowded, since I have to move things around to get 2 keyboards and 2 mice on my desk. And, of course, I don't have the copy/paste across computers :-(

**Comment by Jnewbon** [comment] 2019-05-01 14:34
I'm going to link this to #6487 as I feel they are very similar.

**Comment by jgindin** [comment] 2019-05-08 15:30
@Jnewbon Is there any update on having a fix for this?

**Comment by Jnewbon** [comment] 2019-05-08 17:28
@jgindin not at the moment we are currently pushing out a release and work on this issue didn't make it into the sprint.

**Comment by jgindin** [comment] 2019-05-08 17:42
@Jnewbon When can we expect this fix to make synergy usable again?

**Comment by tavise** [comment] 2019-05-13 19:38
Definitely impacted by this, pretty unusable.

**Comment by ezakto** [comment] 2019-05-13 20:16
I have some extra experience about this. Looks like (at least in my case) it happens in combination with other apps running. For example, when I have Sublime Text open, this bug is incredibly annoying - but when I'm using VS Code, the freezes barely happen, or not at all.
If I use Sublime Text without Synergy, the error doesn't happen, so it's not Sublime. It's the mix for some reason. Hope this helps somehow!

**Comment by StreetGuru** [comment] 2019-05-22 22:47
I just encountered this issue today when upgrading the computer from Mint 18 to Mint 19 (ubuntu 16 to ubuntu 18).
After removing the latest synergy_1.10.2.stable_b10+8c010140_ubuntu18_amd64 and installing synergy_1.10.1.stable_b87+8941241e_debian_amd64 the problem seems to be solved. I'm running sublime text and hadn't had a freeze on the machine since.

**Comment by deanranderson** [comment] 2019-05-28 14:39
I've been testing with getWindowProperty disabled for a couple of weeks now.  It definitely fixed my biggest issue (dragging widgets in Qt apps).   I still see other freezes, though usually not very frequently or as severe.

But today, I was opening a PDF in Okular (KDE Qt based reader) and had several freezes in a row.  And doing some GUI layout with qt designer the other day caused enough freezes to be annoying too.

Other than copy-and-paste not working from client to server, the fix is much more usable than stable.

**Comment by tylerluu** [comment] 2019-05-31 21:29
I had the same issue w/ Ubuntu 16.04 Server and Windows 10 client. For whatever reason, the issue goes away when I turn on Debug2. Is the issue timing related?

**Comment by jgindin** [comment] 2019-07-01 12:49
Can anyone comment on the status here? I've been unable to use Synergy for months now. I'd *love* to have this working again.

**Comment by deanranderson** [comment] 2019-07-01 13:18
There are builds on the forums with a _hack_ that seems to reduce this problem.  It breaks copy and paste from client to server though.
https://members.symless.com/forums/topic/5846-some-observations-about-the-screenmouse-freezing-problem/?tab=comments#comment-28930

**Comment by jgindin** [comment] 2019-07-01 14:28
A reduction is still scary from my standpoint, If, as I had happen before, the problem kicks in while using the command line it's all too easy to use muscle memory to recall a recent command and execute it. But, if the key repetition (see my comment on April 30), you can wind up having a different, possibly destructive command executed.

Same with the freezing. It's all too possible to have the mouse freeze, while you're trying to move to another window and start typing. 

Less frequent is still a serious problem, and doesn't make it useable.

**Comment by tavise** [comment] 2019-07-10 15:25
As @jgindin said, this is currently completely useless to me.  Any progress on this issue?

**Comment by ArcherDs** [comment] 2019-07-18 01:41
I have this issue after i upgrade some packages on  ubuntu,
then I rollback these packages and the issue is gone .

sudo apt install libx11-xcb-dev:amd64=2:1.6.4-3ubuntu0.1 libx11-6:amd64=2:1.6.4-3ubuntu0.1 libx11-6:i386=2:1.6.4-3ubuntu0.1 libx11-data:amd64=2:1.6.4-3ubuntu0.1 libx11-dev:amd64=2:1.6.4-3ubuntu0.1 libx11-doc:amd64=2:1.6.4-3ubuntu0.1 libx11-xcb1:amd64=2:1.6.4-3ubuntu0.1 libx11-xcb1:i386=2:1.6.4-3ubuntu0.1

sudo apt-mark hold  libx11-6 libx11-6:i386 libx11-data libx11-dev libx11-doc libx11-xcb-dev  libx11-xcb1 libx11-xcb1:i386

**Comment by Jnewbon** [comment] 2019-07-18 09:45
@ArcherDs 

I can confirm this eliminates the issue for me on Ubuntu 18, 

I only needed to run the command `sudo apt  install libx11-6=2:1.6.4-3ubuntu0.1` its either this package or one of the packages it pulls down

I upgraded to the latest version again and the issue came back.

**Comment by deanranderson** [comment] 2019-07-18 12:23
Looks like downgrading resolves #6487  Will keep testing to look for intermittent freezes.

The Ubuntu change log for 2:1.6.4-3ubuntu0.2 is interesting.  I haven't looked at the code diffs yet:
```
libx11 (2:1.6.4-3ubuntu0.2) bionic; urgency=medium

  * call-poll-for-event-again.diff: Fix constant video freezes on
    firefox with amdgpu. (LP: #1815125)

 -- Timo Aaltonen <tjaalton@debian.org>  Thu, 07 Feb 2019 22:04:25 +0200
```

I did have to downgrade all the above packages, listed above, not just libx11-6.  Probably because I had installed the dev package or some other dependency.

**Comment by Jnewbon** [comment] 2019-07-18 13:14
@deanranderson Yeah I'm looking into that currently, the descriptions sounds too similar to be a coincidence.

The diffs are [here](https://gitlab.freedesktop.org/xorg/lib/libx11/merge_requests/1/diffs) and I'm currently trying to locate the call path from Synergy that results in that function, as it looks like now instead of returning null like before they are keeping the loop running till a return (I might be wrong I didn't look too deeply at it)

I want to try to locate all paths that would call that particular x11 function as with people reporting the hack as better but not fixed leads me to believe there are other calls into it.

I have already downloaded the libx11-6 source and QT source, but tracing it will be arduous.

**Comment by rhodesm** [comment] 2019-07-26 18:38
I can also verify that downgrading libx11 resolves this issue for me as well. Removing the version pin and updating causes the issue to return.

Server: Windows 10 Build 1809
Client: Ubuntu 18.04 LTS

**Comment by nfstern** [comment] 2019-07-27 17:14
I noticed looking at my Ubuntu 18.04 client that there's a libx11-data with the same version installed.  Do I need to downgrade that also?

**Comment by nhorvath** [comment] 2019-07-28 14:24
I experience this on 19.04 as well. Have been dealing with it for months and did a reinstall to see if it would help. It did not. Then I found this thread. Is there any progress on fixing this inside synergy?

**Comment by dzanotto** [comment] 2019-08-17 16:47
Same problem here too.
Server and client: Ubuntu 18.04 LTS
I'll try the downgrade of libx11 in the next days.
Is the solution of this bug at least planned?

**Comment by nhorvath** [comment] 2019-09-04 15:47
New synergy release today and nothing for this issue? Synergy is extremely frustrating to use on Ubuntu 19.04 because of this and there is no workaround because you can't downgrade libx11.

**Comment by blitzcrege** [comment] 2019-09-06 14:12
Also experiencing this issue on Ubuntu 18.04.3 LTS.

**Comment by arauschsylphen** [comment] 2019-09-27 11:31
I'm having this issue too.
Ubuntu : 18.04. LTS

would be great to have a fix in upcoming synergy release

**Comment by deanranderson** [comment] 2019-09-27 13:56
Yeah, any progress?  I would put this in "showstopper" category, but there hasn't been an official update in a while, and instead Linux gets tweaks to the tray icon...

Has any attempt been made to report the conflict with the Ubuntu team maintaining libX11?

**Comment by jgindin** [comment] 2019-10-02 12:08
Agree on "shipstopper" status. Please...can this get worked on and fixed ASAP?

**Comment by rfoster55** [comment] 2019-10-12 23:41
Same problem here using Ubuntu 18.04 server and client.  Appears to be a client (synergyc) problem with libx11-6.

Downgrading libx11-6 on the client seemed to be enough to fix it for me.  Server still on "2:1.6.4-3ubuntu0.2 amd64"

**Comment by brianhks** [comment] 2019-10-15 19:40
I turned debug log on while this happened to me and this is what I get:

> [2019-10-15T13:20:30] DEBUG2: msg from server: DKUP
[2019-10-15T13:20:30] DEBUG2: readf(%2i%2i%2i)
[2019-10-15T13:20:30] DEBUG2: readf: read 2 byte integer: 108 (0x6c)
[2019-10-15T13:20:30] DEBUG2: readf: read 2 byte integer: 8192 (0x2000)
[2019-10-15T13:20:30] DEBUG2: readf: read 2 byte integer: 46 (0x2e)
[2019-10-15T13:20:30] DEBUG1: recv key up id=0x0000006c, mask=0x2000, button=0x002e
[2019-10-15T13:20:30] DEBUG1: keystrokes:
[2019-10-15T13:20:30] DEBUG1:   02e (00000000) up
[2019-10-15T13:20:30] DEBUG2: writef(CNOP)
[2019-10-15T13:20:30] DEBUG2: wrote 4 bytes
[2019-10-15T13:20:30] DEBUG2: writing secure socket: 0x55a1cdd9ec00
[2019-10-15T13:20:31] DEBUG2: reading secure socket
[2019-10-15T13:20:31] DEBUG2: reading secure socket
[2019-10-15T13:20:31] DEBUG2: want to read, error=2, attempt=1
[2019-10-15T13:20:31] DEBUG2: msg from server: DKDN
[2019-10-15T13:20:31] DEBUG2: readf(%2i%2i%2i)
[2019-10-15T13:20:31] DEBUG2: readf: read 2 byte integer: 61197 (0xef0d)
[2019-10-15T13:20:31] DEBUG2: readf: read 2 byte integer: 8192 (0x2000)
[2019-10-15T13:20:31] DEBUG2: readf: read 2 byte integer: 36 (0x24)
[2019-10-15T13:20:31] DEBUG1: recv key down id=0x0000ef0d, mask=0x2000, button=0x0024
[2019-10-15T13:20:31] DEBUG1: mapKey ef0d (61197) with mask 2000, start state: 2000
[2019-10-15T13:20:31] DEBUG1: find best:  2000 2000
[2019-10-15T13:20:31] DEBUG1: best key index 1 of 1 (exact)
[2019-10-15T13:20:31] DEBUG1: found key in group 0
[2019-10-15T13:20:31] DEBUG1: state: 2000,0000,0000
[2019-10-15T13:20:31] DEBUG1: flip: 0000 (2000 vs 0000 in 0000 - 0000)
[2019-10-15T13:20:31] DEBUG1: desired state: 2000 2000,0000,0000
[2019-10-15T13:20:31] DEBUG1: flip: 0000 (2000 vs 2000 in ffff - 6020)
[2019-10-15T13:20:31] DEBUG1: mapped to 024, new state 2000
[2019-10-15T13:20:31] DEBUG1: keystrokes:
[2019-10-15T13:20:31] DEBUG1:   024 (00000000) down
[2019-10-15T13:20:31] DEBUG2: writef(CNOP)
[2019-10-15T13:20:31] DEBUG2: wrote 4 bytes
[2019-10-15T13:20:31] DEBUG2: writing secure socket: 0x55a1cdd9ec00
[2019-10-15T13:20:31] DEBUG2: can't read property 579 on window 0x04006b73
[2019-10-15T13:20:31] DEBUG2: can't read property 579 on window 0x00400003
[2019-10-15T13:20:31] DEBUG2: reading secure socket
[2019-10-15T13:20:31] DEBUG2: reading secure socket
[2019-10-15T13:20:31] DEBUG2: want to read, error=2, attempt=1
[2019-10-15T13:20:31] DEBUG2: reading secure socket
[2019-10-15T13:20:31] DEBUG2: reading secure socket
[2019-10-15T13:20:31] DEBUG2: want to read, error=2, attempt=1
[2019-10-15T13:20:31] DEBUG2: reading secure socket
[2019-10-15T13:20:31] DEBUG2: reading secure socket
[2019-10-15T13:20:31] DEBUG2: want to read, error=2, attempt=1
[2019-10-15T13:20:32] DEBUG2: reading secure socket
[2019-10-15T13:20:32] DEBUG2: reading secure socket
[2019-10-15T13:20:32] DEBUG2: want to read, error=2, attempt=1
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: want to read, error=2, attempt=1
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: want to read, error=2, attempt=1
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: want to read, error=2, attempt=1
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: want to read, error=2, attempt=1
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: want to read, error=2, attempt=1
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: want to read, error=2, attempt=1
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: want to read, error=2, attempt=1
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: want to read, error=2, attempt=1
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: want to read, error=2, attempt=1
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: want to read, error=2, attempt=1
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: want to read, error=2, attempt=1
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: want to read, error=2, attempt=1
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: want to read, error=2, attempt=1
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: want to read, error=2, attempt=1
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: want to read, error=2, attempt=1
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: want to read, error=2, attempt=1
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: want to read, error=2, attempt=1
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: reading secure socket
[2019-10-15T13:20:33] DEBUG2: want to read, error=2, attempt=1
[2019-10-15T13:20:33] DEBUG2: msg from server: DKUP
[2019-10-15T13:20:33] DEBUG2: readf(%2i%2i%2i)
[2019-10-15T13:20:33] DEBUG2: readf: read 2 byte integer: 61197 (0xef0d)
[2019-10-15T13:20:33] DEBUG2: readf: read 2 byte integer: 8192 (0x2000)
[2019-10-15T13:20:33] DEBUG2: readf: read 2 byte integer: 36 (0x24)
[2019-10-15T13:20:33] DEBUG1: recv key up id=0x0000ef0d, mask=0x2000, button=0x0024
[2019-10-15T13:20:33] DEBUG1: keystrokes:
[2019-10-15T13:20:33] DEBUG1:   024 (00000000) up
[2019-10-15T13:20:33] DEBUG2: writef(CNOP)
[2019-10-15T13:20:33] DEBUG2: wrote 4 bytes
[2019-10-15T13:20:33] DEBUG2: writing secure socket: 0x55a1cdd9ec00
[2019-10-15T13:20:33] DEBUG2: msg from server: DKDN

Notice it gets a key down and then a bunch of errors before it gets a key up.  During this time the mouse freezes and I get a bunch of carriage returns in my code I was typing.

I've tried it with and without secure socket and it doesn't seem to make a difference.

**Comment by nbolton** [comment] 2019-10-25 06:48
Duplicates #6487

**Closed by nbolton** 2019-10-25 06:48 UTC
Labels: triage
