### ISSUE TITLE
Server process is allocating gigabites of memory on Linux

### ISSUE THREAD

**Issue by AlexeyPilya** [symless/synergy-core#6482] opened 2019-04-17 10:52 UTC
### Operating Systems ###

Server: Linux
Client: MacOS Mojave

### Synergy Version ###

1.10.1

### Issue Description###

On linux Synergy Server the app it's allocating 16GB of ram

[2019-04-17T05:55:55] INFO: switch from "MBP" to "lolita" at 3838,315
[2019-04-17T05:55:55] INFO: entering screen
[2019-04-17T05:55:55] INFO: switch from "lolita" to "MBP" at 0,606
[2019-04-17T05:55:55] INFO: leaving screen
[2019-04-17T05:55:55] INFO: switch from "MBP" to "lolita" at 3826,264
[2019-04-17T05:55:55] INFO: entering screen
[2019-04-17T05:55:55] INFO: switch from "lolita" to "MBP" at 0,634
[2019-04-17T05:55:55] INFO: leaving screen
[2019-04-17T05:55:55] INFO: switch from "MBP" to "lolita" at 3838,375
[2019-04-17T05:55:55] INFO: entering screen
[2019-04-17T05:55:55] INFO: switch from "lolita" to "MBP" at 0,644
[2019-04-17T05:55:55] INFO: leaving screen
[2019-04-17T05:55:55] INFO: switch from "MBP" to "lolita" at 3838,194
[2019-04-17T05:55:55] INFO: entering screen
[2019-04-17T05:55:56] INFO: switch from "lolita" to "MBP" at 0,557
[2019-04-17T05:55:56] INFO: leaving screen
[2019-04-17T05:55:56] INFO: switch from "MBP" to "lolita" at 3838,251
[2019-04-17T05:55:56] INFO: entering screen
[2019-04-17T05:55:56] INFO: switch from "lolita" to "MBP" at 0,661
[2019-04-17T05:55:56] INFO: leaving screen
[2019-04-17T05:55:56] INFO: switch from "MBP" to "lolita" at 3829,342
[2019-04-17T05:55:56] INFO: entering screen
[2019-04-17T05:55:56] INFO: switch from "lolita" to "MBP" at 0,421
[2019-04-17T05:55:56] INFO: leaving screen
[2019-04-17T05:55:56] INFO: switch from "MBP" to "lolita" at 3834,421
[2019-04-17T05:55:56] INFO: entering screen
[2019-04-17T06:01:47] INFO: switch from "lolita" to "MBP" at 0,59
[2019-04-17T06:01:47] INFO: leaving screen
[2019-04-17T06:01:47] INFO: screen "lolita" updated clipboard 0
[2019-04-17T06:01:47] INFO: screen "lolita" updated clipboard 1
[2019-04-17T06:01:48] INFO: switch from "MBP" to "lolita" at 3838,66

![synergy](https://user-images.githubusercontent.com/43998106/56289673-2643a980-612a-11e9-9057-c2b305c5150e.png)

**Comment by liyoubdu** [comment] 2019-04-18 07:29
bad memery

**Comment by mvduin** [comment] 2019-04-25 12:49
Presumably duplicate of #6460 ?

**Comment by catrielmuller** [comment] 2019-04-25 12:52
> Presumably duplicate of #6460 ?

Yes it's the same issue

**Comment by Jnewbon** [comment] 2019-04-25 14:40
Closed, As it's a duplicate of #6460

**Closed by Jnewbon** 2019-04-25 14:40 UTC
