### ISSUE TITLE
Centos 7

### ISSUE THREAD

**Issue by zayajf** [symless/synergy-core#6602] opened 2019-12-03 17:41 UTC
### Centos ###

---BEGIN HELP---

Remember: Delete the help text (between `---BEGIN HELP---` and `---END HELP---`).
Technical support: https://symless.com/contact/customer-support?help-option=GitHub

For example:

Server: Windows 10
Client: Centos 7 3.10

Please distinguish which operating system is the client and which is the server. The server is the computer that the mouse and keyboard are shared from.

---END HELP---

### Synergy Version ###

---BEGIN HELP---

If you're not using the latest version of Synergy, please update first:
https://symless.com/synergy/downloads

Please don't rely on Linux package manager versioning, they often get it wrong. If using the command line, you can use the `--version` arg to get your installed Synergy version, like so:

Synergy 1: `synergys --version`
Synergy 2: `synergy-core --server --version`

If you're using the Synergy 1 config app (main Synergy app) then go to the Help menu, and click About. In Synergy 2 Beta, the version is displayed at all times.

---END HELP---

### Steps to Reproduce ###

---BEGIN HELP---

This is the most important part. Try to remember exactly what exact steps caused the bug. Please make sure the steps are numbered and concise, like so:

After building with CMAKE
Make command fails 75% 

```
**[ 74%] Building CXX object src/gui/CMakeFiles/synergy.dir/synergy_autogen/mocs_compilation.cpp.o
In file included from /opt/synergy-core/build/src/gui/synergy_autogen/UVLADIE3JM/moc_ZeroconfRegister.cpp:9:0,
                 from /opt/synergy-core/build/src/gui/synergy_autogen/mocs_compilation.cpp:31:
/opt/synergy-core/build/src/gui/synergy_autogen/UVLADIE3JM/../../../../../src/gui/src/ZeroconfRegister.h:32:20: fatal error: dns_sd.h: No such file or directory
 #include <dns_sd.h>
                    ^
compilation terminated.
make[2]: *** [src/gui/CMakeFiles/synergy.dir/synergy_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [src/gui/CMakeFiles/synergy.dir/all] Error 2
make: *** [all] Error 2**

```

---END Help----

**Comment by Jnewbon** [comment] 2019-12-04 09:54
Duplicate of #6532 

Please see https://github.com/symless/synergy-core/issues/6532#issuecomment-509148772

**Closed by Jnewbon** 2019-12-04 09:54 UTC
Labels: bug, triage
