### ISSUE TITLE
Server login screen causes cursor lockout on client

### ISSUE THREAD

**Issue by willichan** [symless/synergy-core#5075] opened 2015-10-30 21:51 UTC
Running synergy-v1.7.5-rc1-ceab3a8 on both machines
Server:  Windows 7 Enterprise SP1 64-bit (on left)
Client:  Linux Mint 17.2 Cinnamon 64-bit (on right)

If both systems are showing a login or unlock screen, and I move the mouse beyond the right edge of the server display, the mouse does not appear on the client display.  Even though the mouse is not displaying, the client has control of it, and moving the mouse back to the left will not return it to the server display.  In essence, control is now trapped on the client, where you cannot actually do anything with it.

The only way to unlock the systems once this happens is:
1.  Use a keyboard/mouse connected to the client PC to enter the password and unlock the client.
2.  Kill and restart the synergyc process.
   The server will again be able to control the mouse/keyboard.

**Comment by jpnoel** [comment] 2015-12-09 13:24
I have same issue running 1.7.5 with Win10 server and Linux/Mac clients. Bug occurs if im on lock screen of win10 and I touch either the left side (linux) or right side (Mac) of my windows lock screen

**Comment by needleshaped** [comment] 2015-12-29 22:18
Windows 10  - Synergy server
Gentoo Linux - Synergy client
1.7.5 version both.

Reproducible: always.

Steps to reproduce:
1. Lock Win10 (i.e. Win+L)
2. Move mouse to configured border with other monitor. For few seconds nothing happens (while Synergy does desk switches to activeDesktop:Winlogon), then:

Result: 
1. Focus stuck on Linux/client (no way to unlock Win10)
2. Keyboard works - on Linux/client only.
3. Mouse cursor become useless:
3a. Mouse cursor stops at Win/server screen border. Disappears when anything is typed on keyboard.
3b. Mouse cursor also appears on Linux/client side (on border as well, and at the same time, so each monitor have cursors), but then seems to disappear if mouse is moved.

Log: [synergy_issue_5075.log.txt](https://github.com/synergy/synergy/files/74396/synergy_issue_5075.log.txt). After focus stuck on client side, I kill client process. 
Config: [probe_synergy.sgc.txt](https://github.com/synergy/synergy/files/74398/probe_synergy.sgc.txt)

**Comment by fievel** [comment] 2016-01-29 12:39
I have the same behavior between a windows 7 server and a linux client on 1.7.5 version. It's very annoying.

**Comment by sunk818** [comment] 2016-04-20 19:23
I think this is my issue as well. I lock my Windows 7 machine (server) when I go to lunch. Come back and I don't have keyboard mouse control. I have to exit synergy on my Mac (client) to regain control of the keyboard and mouse.

**Comment by rlaban** [comment] 2016-05-19 08:25
Similar issue here: 

server: win7
client: win10

Server has auto-lock enabled. Every now and then when server locks (either manually or auto), the focus gets stuck on the client (no mouse at all, but keyboard presses end up on client). Workaround is pulling network plug from client (laptop) and after a number of seconds the mouse becomes responsive on the server again. Then I insert network plug again and Synergy is operational again.

**Comment by Endareth** [comment] 2016-06-20 06:32
Same issue.
Server: Win 8.1
Client: OS X 10.11.5, 10.12.0
Synergy: v1.7.4
Luckily I still have a trackpad on the Mac, and can toggle Synergy off then on.

**Comment by vmystic** [comment] 2016-08-19 17:13
Same issue for me as well
Server: Windows 7 Enterprise SP1
Client: CentOS 7.2.1511
Synergy: 1.8.2-stable

**Comment by ELind77** [comment] 2016-09-06 16:36
I also have this issue:
Synergy version: 1.8.2
Server:  Windows 10 Pro x64 (v 1607)
Client: OS X 10.11.6

I've had the issue both before and after the Win 10 1607 update.

This issue has been marked as a bug with no one assigned since November 2015, is there a workaround that doesn't require using an input device on the client (thus defeating the point of Synergy)?

-- Eric

**Comment by nlyan** [comment] 2016-09-07 10:21
Lock screen improvements are planned soon. So I'll be looking in to this.

**Comment by trpt4him** [comment] 2016-09-21 11:39
Same issue here, Win 7 both server and client.  When I lock both server and client, if I move the cursor back and forth on the server machine, after about 5 seconds the cursor will get stuck if I move the cursor to the far left side, at what I guess would be x-position 0.  It "sticks" to the left side.

**Comment by hgword** [comment] 2016-10-14 05:06
synergy 1.8.3
Server : Windows7
Client : mac mini (os 10.12)/ macbook pro (os 10.11.6)

same issue occur

**Comment by MistarMuffin** [comment] 2016-10-18 18:09
Server: Windows 7
Client: Linux Mint 18
Synergy 1.8.4

When I lock the server with Win+L the client does not lock with it. So I take the mouse and go to the edge of the screen to try to lock the Linux client manually. Once the mouse passes the edge of the server screen it disappears. The mouse is invisible on the client but you can see UI controls react when the mouse hovers over them. You cannot click or interact but the keyboard works. I have to use term to kill synergyc in order for the mouse to pop back on the server. Can duplicate every time.

**Comment by fatfatson** [comment] 2016-10-30 15:50
Server: Windows 7
Client: Windows 10
Synergy 1.8.4

same issue occur

**Comment by GitSweendog** [comment] 2016-11-10 16:15
Same problem here.  Running 3 Win7 64 systems.  Easy to reproduce:
1. Lock Windows workstation running Synergy Server
2. Move mouse cursor to either edge of Server - Client border.
3. Mouse locks at border and becomes unusable.  
The only work-around I have right now is to dig out the client system mouse, pull up the Synergy Client, and stop/start the client.  When the client stops, the mouse is freed up on the Sever edge again.

**Comment by fatjack** [comment] 2016-12-01 22:57
Same problem.

Server: Debian 8.6 (with 4.7 kernel)
Client: Windows 10 Enterprise
Synergy Version: 1.8.5

Can reproduce with:
1.) Lock Windows 10
2.) Unable to move mouse from server to client until about 4-5 seconds later. 

Also happens with some mmc screens.

**Comment by thehans** [comment] 2016-12-06 22:25
Also experiencing this issue:
Server: Windows 7 Pro 64bit
Client: Linux Mint 17.3 64bit
Synergy version: 1.8.5-stable-a18eba7 on both

Please fix this!

**Comment by ALenfant** [comment] 2017-03-22 05:01
Same here, really really annoying as my server is a macbook pro and my client a mac mini

**Comment by ra33it** [comment] 2017-03-27 15:56
1.8.7 Stable Windows 7 Server 
1.8.8 Stable Fedora 25 Client

Windows L does lock both screens but I find the linux client always ends up with the cursor, which won't return back to the windows 7 server machine. I find unplug/plug of the keyboard or mouse will often restore the mouse.

**Comment by rbabiak** [comment] 2017-03-27 16:31
1.8.5-stable-a18eba7 Windows 7 Server (64bit)
1.8.5-stable-a18eba7 Mac OSX Client

Basically have stopped using the product I paid for as this happens multiple a times a week.

**Comment by the-spyke** [comment] 2017-03-27 18:52
Happens to me too (Windows 10 host + Ubuntu 16.04 client). I set up shortcuts to switch cursor between screens. When cursor stuck at the corners, I press a shortcut to move cursor to the host's screen, and it becomes possible to enter a password.

**Comment by zrajnai** [comment] 2017-03-28 07:11
Also happens on:
Server: Windows 10 Pro 64bit 1607    14393.693
Client: Windows 7 Pro 64bit SP1

**Comment by TheFatherMind** [comment] 2017-04-05 04:09
Server: Windows 8.1
Client: Windows 7
Version: 1.8.8

I am also having this issue.
This seems like a pretty serious bug.  Why is it being ignored for so long?

**Comment by vanowm** [comment] 2017-04-21 11:10
The client PC doesn't need to be locked for this bug to be reproduced.

**Comment by MistarMuffin** [comment] 2018-06-21 20:35
Nick,

Why are you closing this bug and marking it as stale when you know it still exists in 2.0.12? I have reported it directly to Symless support multiple times. The most recent report on June 11th you responded to directly by offering me a refund. I think everyone would rather see you actually fix the bugs in Synergy rather than just pretending like they don't exist.

**Comment by TheFatherMind** [comment] 2018-10-19 21:02
I have to keep my lock screens because of security and stuff.. but if you are willing to forgo that.. Here are some places to look...

To make your computer auto-login at startup
use the "Run" dialog and run the following: netplwiz
You can also go to a command prompt and type: start netplwiz
You will get a Windows XP style dialog.
On that dialog you will see a checkbox.  Uncheck it and apply.  You will be prompted for your login credentials.
Perhaps microsoft has provided a better way to manage this.  I have never found it.  This works on all versions of windows.

To stop it from locking after set amount of time...
Go to "Personalization" then "Screen Saver" and make sure "On Resume display login screen" is unchecked.  (Also a Windows XP dialog, god bless you Microsoft for never actually finishing an OS :).

Also check...
Go to "Power Options" in the control panel.
On left choose "Require Password on Wakeup"  (may be different in Win10)
If the options are dimmed out/unchangeable then look for the link near the top that says, "Change Settings that are currently unavailable" first.

If this does not do it for you.  Report back and I will help you further.

**Comment by ne0hisda0ne** [comment] 2018-11-14 19:57
This works...

https://github.com/symless/synergy-core/issues/5294#issuecomment-318669465

**Comment by deftoner** [comment] 2018-11-15 21:09
Great idea (shortcut to change screen)  thanks

**Comment by Jnewbon** [comment] 2019-10-09 09:28
Duplicate of #5294

**Closed by Jnewbon** 2019-10-09 09:28 UTC
Labels: bug

**Comment by kanebryant** [comment] 2020-12-08 05:11
Call me stupid but I just installed this thing and this bug still exists 5 years after it was raised???? You would think with COVID
bug fixes would have been a priority to get the core features working fluidly .

**Comment by DesktopMasters** [comment] 2020-12-08 05:39
I could be mistaken here but they started a 2.0 version that is not actually 2.0 but what seems like a complete rewrite.  Once they got all the "pre signups" they stopped working on it.  And it feels like they abandoned this version of it for the new one that they never finished.  It is sad too because I really like this product and would gladly give them more money when they complete it to have a better more stable version of it and to support them.
