### ISSUE TITLE
MacOS v.1.11.1 application is blurry and unfocused

### ISSUE THREAD

**Issue by ajak7** [symless/synergy-core#6858] opened 2020-12-01 11:13 UTC
I am having an issue where the Synergy application is blurry and unfocused.
Attached bellow is a screenshot of what it looks like. The application is running well, and everything else is working as intended, but the unfocused part is a bit annoying.
The windows version does not have this problem (amazing, right?). What can I do to fix this?

<img width="742" alt="Synergy" src="https://user-images.githubusercontent.com/53130125/100733352-55c22b00-33ce-11eb-9fe8-3240e8df7174.png">

EDIT:
Doing a bit of research I found an app called "Retinizer" which solved my problem.
I think the issue might be that Synergy is not optimised for Retina displays, so what Retinizer does is it forces the selected application to run in Retina mode.
Download link: http://retinizer.mikelpr.com

**Comment by bellerofonte** [comment] 2020-12-07 10:46
+1
This issue has been existing for at least 3 years (since I've started to use Synergy)

**Comment by andreacndn** [comment] 2020-12-17 09:10
@ajak7 , @bellerofonte could you please try Synergy 1.13.0 release candidate 2 and confirm if the problem is resolved?
https://symless.com/synergy/releases/synergy-1-13-release-candidate-2

Thanks,
Andrea

**Comment by bellerofonte** [comment] 2020-12-17 09:14
Ver 1.13rc2 is still blurry.
Issue is NOT resolved
![image](https://user-images.githubusercontent.com/5753506/102467443-5959e100-4061-11eb-83c3-261be4f354d2.png)

**Comment by andreacndn** [comment] 2020-12-17 09:49
Apologies, my bad, the fix is included in the final release and not in the release candidate.
Will keep you posted.

**Comment by andreacndn** [comment] 2021-01-03 15:03
Fixed in 1.13.0

**Closed by andreacndn** 2021-01-03 15:03 UTC
Labels: bug, triage

**Comment by bellerofonte** [comment] 2021-01-08 07:58
ver. 1.13.0-stable - still blurry 🙁
![image](https://user-images.githubusercontent.com/5753506/103989118-476ee800-51a0-11eb-822b-65b508f824b5.png)
