### ISSUE TITLE
After installation on Ubuntu 17.10, synergy not works

### ISSUE THREAD

**Issue by Aleinux** [symless/synergy-core#6192] opened 2017-11-09 14:15 UTC
### Operating Systems ###

Server: Ubuntu 17.10

After installation on Ubuntu 17.10, synergy not works

### Synergy Version ###

2.0 stable

**Comment by flyinprogrammer** [comment] 2017-11-11 22:08
unfortunately they don't support [wayland](https://wiki.ubuntu.com/Wayland) yet, so their Ubuntu support is only a partial truth: https://github.com/symless/synergy-core/issues/4090

**Comment by XinyuHou** [comment] 2017-11-23 12:40
Duplicate of #4090

There is a workaround to disable wayland to get Synergy working. Please check #4090

**Closed by XinyuHou** 2017-11-23 12:40 UTC
