### ISSUE TITLE
MotionNotify not firing on Gome Wayland unles application is under mouse

### ISSUE THREAD

**Issue by wirecat** [symless/synergy-core#6196] opened 2017-11-17 23:03 UTC
### Operating Systems ###

Server: 4.13.12-1-ARCH running Gnome Wayland 3.26.2
Client: 4.13.12-1-ARCH running Gnome Wayland 3.26.2

### Synergy Version ###

1.8.8 and 2.0.0

### Steps to reproduce bug ###

Create a simple config that has a left and right combination of server and client. I'll put my configuration below. Doesn't matter if client is left or right of server. Minimize all windows so you only view your desktop and try to move mouse to the client. The mouse should not move to client. If you change synergy logging level to Debug2 you can see no MotionNotify events being fired. If you fullscreen an application like chrome, firefox, or the synergy GUI you will see MotionNotify events across that windows. Fullscreening that window on your boundary and then trying to move to client will result in the mouse successfully moving to the client.

### Other info ###

* This problem is intermittent? It seems that sometimes it works without having an application fullscreened.

### My Config ###
```
section: screens
   gilliam:
   danijohnlx2:
end

section: links
   danijohnlx2:
      right = gilliam
   gilliam:
      left = danijohnlx2
end
```

**Comment by wirecat** [comment] 2017-11-20 23:26
This has become more mysterious for me... I setup a config to switch to client using keyboard and it acts weird as well. Something odd is going on with focus and if I click in the client, an application on the server will gain focus. The mouse remains active in the client after this happens and I can switch back to server.

**Comment by XinyuHou** [comment] 2017-11-23 13:07
Duplicate of #4090

**Closed by XinyuHou** 2017-11-23 13:07 UTC

**Comment by nbolton** [comment] 2024-08-30 15:41
Fixed by: https://github.com/symless/synergy/pull/7449
