### ISSUE TITLE
Coordinated lock/unlock

### ISSUE THREAD

**Issue by aholmes** [symless/synergy-core#6243] opened 2018-01-19 21:27 UTC
### Operating Systems ###

Server: Windows 7 (Version 6.1 Build 7601 SP 1)
Client: Windows 7 (Version 6.1 Build 7601 SP 1)

### Synergy Version ###

2.0.4-stable

### Other info ###

It would be nice for the key combo `Meta/Windows + L` to lock the server and all clients, and `CTRL+ALT+DEL` (from lock screen) to unlock.

**Comment by judge2020** [comment] 2018-01-23 05:39
By the looks of it, this is going to be a synergy 2 pro feature: https://symless.com/synergy/pricing. Not sure what the policy here is for synergy 2 features/issues since this is the legacy repo.

**Comment by XinyuHou** [comment] 2018-01-26 11:17
Duplicate of #3084

**Closed by XinyuHou** 2018-01-26 11:17 UTC
