### ISSUE TITLE
Synergy + Chrome Canary result in modifiers getting interpreted as cmd+a in the URL bar

### ISSUE THREAD

**Issue by orcinus** [symless/synergy-core#6406] opened 2018-08-24 19:33 UTC
### Operating Systems ###
Mac OS X Mojave 18A365a

### Synergy Version ###
Any, from 1.9.x till 1.10.x.

### Steps to Reproduce ###
1) Install Chrome Canary on the Synergy client machine
2) On the Synergy client machine, click inside the URL bar
3) Hit Ctrl or Cmd
4) Ends up doing a select-all on the contents of the URL field

### Run Method ###
Config app.

### Log URLs ###
Nothing interesting in the logs.

### Extra Info ###
The issue is limited to Chrome Canary only, and appeared in the last few builds. I fully realize it seems like the issue is with Chrome, but consider the following odd details:
- built in keyboard (client is a laptop) does not behave the same
- it appears to be interpreting a modifier as a keystroke (!)
- it only happens with cmd and ctrl for some reason
- when hitting a modifier + a key (e.g. cmd+c), it ends up doing select-all, then copy - i.e. the select-all happens 100% reproducibly before the actual keystroke gets emitted
- it ONLY behaves this way in the address bar, nowhere else (pages are fine, all dialogues are fine)

**Comment by orcinus** [comment] 2018-08-31 15:05
Submitted to Chromium bug tracker as well, but they can't/won't do anything because of the paywall.
https://bugs.chromium.org/p/chromium/issues/detail?id=877710&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=

I'd suggest resubmitting, and giving them access to the binaries.

**Comment by nbolton** [comment] 2018-10-29 07:57
Duplicate of #6430

**Closed by nbolton** 2018-10-29 07:57 UTC
