### ISSUE TITLE
Cursor disappears on OS X (Client) after moving cursor back to host

### ISSUE THREAD

**Issue by RENMX** [symless/synergy-core#4707] opened 2015-05-25 16:28 UTC
Easy to reproduce on my own setup. I'm using Windows 8.1 with all the latest windows updates as the host, I'm using Mac OS X 10.10.3 Yosemite as the client.

When I move the cursor to the OS X system, it works perfectly I can move it around and see it. When I move the cursor back to the host and then try to use the native mouse on my Mac the cursor is invisible. I can still click on things, move them around on screen but the cursor is invisible.

I have to wildly flail around and click randomly to get the cursor to re-appear. The problem is gone completely if I close Synergy on my Mac.

**Comment by speaker** [comment] 2015-06-16 16:14
The disappearing pointer is a feature actually, getting it back w/o using synergy, however, is another matter. You should only need to click the mouse once without moving it around to bring it back into view. 

Is this still happening?

**Comment by RenMX** [comment] 2015-06-16 16:19
That is really confusing behaviour because when you move the cursor around without clicking, the UI of OS X responds as if the mouse is there but hidden. So I become afraid to click incase I accidentally close something in the UI due to it reacting to the mouse movement even though I can't see the cursor on screen.

I wasn't aware you could click to bring the cursor back, that does work. I would however prefer the mouse to just re-appear if it senses movement on the system that owns the cursor. Perhaps a toggle setting could cater to both use scenarios?

**Comment by speaker** [comment] 2015-06-16 23:32
@RenMX , That's not a bad idea at all. I must admit to being a little confused myself a few times when the mouse briefly wandered onto my mac unintentionally.

**Comment by tsnieman** [comment] 2015-09-23 19:24
I'd just like to note that I have the aforementioned "cursor disappearing from client after moving cursor back to host", and that clicking **doesn't** bring it back into view. I have found one way to make it visible again: opening Mission Control.

I would like the toggle option though.

**Comment by mrsixw** [comment] 2018-02-14 14:15
Duplicate of #2754

**Closed by mrsixw** 2018-02-14 14:15 UTC
Labels: bug

**Comment by vldmatos** [comment] 2020-06-12 01:51
Try set option: check clients every on Advanced server settings, the problem stopped occurring.
