### ISSUE TITLE
Windows uninstall shows Files in Use dialog

### ISSUE THREAD

**Issue by Jnewbon** [symless/synergy-core#6501] opened 2019-05-14 11:43 UTC
### Operating Systems ###

Windows 10

### Synergy Version ###

1.10.2

### Steps to Reproduce ###

1. Try to uninstall (or reinstall) on Windows
2. See "Files in Use" dialog (see screenshot)
3. Kill all programs listed to continue the install

### Extra Info ###

Fix: Backport #6226

![image](https://user-images.githubusercontent.com/48688400/57695142-64f35380-7645-11e9-8d71-bd399f613806.png)

**Comment by nbolton** [comment] 2019-11-13 09:53
Duplicate of #4957

**Closed by nbolton** 2019-11-13 09:53 UTC
Labels: bug, triage
