### ISSUE TITLE
Connect to VPN on Client causes Client to stop working

### ISSUE THREAD

**Issue by gmills12** [symless/synergy-core#6177] opened 2017-10-20 18:21 UTC
### Operating Systems ###

Server: Windows 10 Home Version 1703
Client: Windows 7 Enterprise Version 6.1
### Steps to reproduce bug ###

1.Connect Client to Server.
2. Login into VPN on Client.
3. Bug occurs.

### Other info ###

* When did the problem start to occur? When I...
* Is there a way to work around it? Not that I know.
* Does this bug prevent you from using Synergy entirely? Yes

Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy-core/wiki/Sending-logs

Put anything else you can think of here.

**Comment by vanbcguy** [comment] 2017-10-20 19:16
Sounds like your VPN blocks connections to things that aren't on the VPN... super common for corporate VPN connections and nothing to do with Synergy...

**Comment by XinyuHou** [comment] 2017-10-25 14:35
Duplicate of #6050

**Closed by XinyuHou** 2017-10-25 14:35 UTC
