### ISSUE TITLE
Ubuntu 20.04 openssl error key too small

### ISSUE THREAD

**Issue by moneyatbo** [symless/synergy-core#6668] opened 2020-04-27 13:27 UTC
### Operating Systems ###
Server: synergy_1.11.1.stable_b58+55ec3105_ubuntu19_amd64
Client: synergy_v1.11.1-stable_b169-55ec3105_windows_x64

---END HELP---
1. upgrade server to Ubuntu 20.04
2. reboot
3. start synergy service
4. see in the synergy log on the server 

[2020-04-27T09:25:57] ERROR: secure socket error: could not use tls certificate
[2020-04-27T09:25:57] ERROR: openssl error: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small

**Comment by Jnewbon** [comment] 2020-04-27 13:29
Duplicate of #6667

**Closed by Jnewbon** 2020-04-27 13:29 UTC
Labels: bug, triage

**Comment by nbolton** [comment] 2020-04-28 11:02
Will be fixed by #6669
