### ISSUE TITLE
Bottoms of screens not lining up causes one screen to become inaccessible

### ISSUE THREAD

**Issue by orcinus** [symless/synergy-core#6150] opened 2017-09-13 22:57 UTC
Server: Windows 10 Creators Update
Client: Mac OS X 10.12.6
Synergy: 1.8.x

I've got two monitors with different resolutions on the server (left: 4k, right: HD). The client has a single monitor lined up below them, centered horizontally. 

If i don't align the two server screens' bottoms in Windows, and instead align them so their vertical centers match (i.e. so that when the cursor transitions from left screen to the right through the vertical center of the side edge), the right server monitor becomes inaccessible from the client. There is, essentially, a "gap" synergy sees between the two monitors, that does not act as a boundary, and thus doesn't allow you to transition between them.

If, however, i line up the bottoms of both screens, i can transition between client and server just fine.

Expected behaviour: Synergy should ignore the dead space between screens and transition between them freely.

**Comment by XinyuHou** [comment] 2017-09-27 12:19
Duplicate of #4173

**Closed by XinyuHou** 2017-09-27 12:19 UTC
